imports:
  - php

tools:
  php_code_sniffer: true
  php_code_coverage: true
  php_mess_detector: true

before_commands:
  - "curl -s http://getcomposer.org/installer | php"
  - "composer install --prefer-source"